In [2]:
import jieba

In [3]:
#精确模式分词 适合文本分析
content = "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作"
jieba.cut(content,cut_all=False)#返回生成器对象
jieba.lcut(content,cut_all=False)#直接返回列表内容，返回全模式，能够分词都分出来

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.622 seconds.
Prefix dict has been built successfully.


['工信处',
 '女干事',
 '每月',
 '经过',
 '下属',
 '科室',
 '都',
 '要',
 '亲口',
 '交代',
 '24',
 '口',
 '交换机',
 '等',
 '技术性',
 '器件',
 '的',
 '安装',
 '工作']

In [4]:
#全模式分词
content = "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作"
jieba.cut(content,cut_all=False)#返回生成器对象
jieba.lcut(content,cut_all=True)#直接返回列表内容，返回全模式，能够分词都分出来

['工信处',
 '处女',
 '女干事',
 '干事',
 '每月',
 '月经',
 '经过',
 '下属',
 '科室',
 '都',
 '要',
 '亲口',
 '口交',
 '交代',
 '24',
 '口交',
 '交换',
 '交换机',
 '换机',
 '等',
 '技术',
 '技术性',
 '性器',
 '器件',
 '的',
 '安装',
 '安装工',
 '装工',
 '工作']

In [5]:
# 搜索引擎模式分词
jieba.cut_for_search(content)

<generator object Tokenizer.cut_for_search at 0x7fe17f9a9930>

In [6]:
jieba.lcut_for_search(content)  #比全模式分词少，比精确模式分词多

['工信处',
 '干事',
 '女干事',
 '每月',
 '经过',
 '下属',
 '科室',
 '都',
 '要',
 '亲口',
 '交代',
 '24',
 '口',
 '交换',
 '换机',
 '交换机',
 '等',
 '技术',
 '技术性',
 '器件',
 '的',
 '安装',
 '工作']

In [7]:
#中文繁体分词
content = "煩惱即是菩提，我暫且不提"
jieba.lcut(content)

['煩惱', '即', '是', '菩提', '，', '我', '暫且', '不', '提']

In [8]:
#使用用户自定义字典
#词语 词频 词性
#西巴罗马给死噶 5 n
jieba.lcut("西巴罗马给死噶")


['西巴', '罗马', '给', '死', '噶']

In [9]:
import os
# dirs="./user_dict.txt/"
# if not os.path.exists(dirs):    
#     os.mkdir("./user_dict.txt")

f=open("user_dict.txt","w")  #a追加到末尾，w 写入覆盖 x写入 默认rb二进制
f.write("西巴罗马给死噶 5 n")
f.close()
f=open("user_dict.txt")
print(f.read())

西巴罗马给死噶 5 n


In [10]:
jieba.load_userdict("./user_dict.txt") #导入用户自定义userdict
jieba.lcut("西巴罗马给死噶吃饭吃什么吃")

['西巴罗马给死噶', '吃饭', '吃', '什么', '吃']

In [11]:
import hanlp

In [12]:
tokenizer=hanlp.load('CTB6_CONVSEG')
tokenizer('"工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作"')
# tokenizer = hanlp.utils.rules.tokenize_english 
# tokenizer('Mr. Hankcs bought hankcs.com for 1.5 thousand dollars.')

['"',
 '工信处',
 '女',
 '干事',
 '每',
 '月',
 '经过',
 '下属',
 '科室',
 '都',
 '要',
 '亲口',
 '交代',
 '24',
 '口',
 '交换机',
 '等',
 '技术性',
 '器件',
 '的',
 '安装',
 '工作',
 '"']

In [13]:
#命名实体识别 比如人名，地名，机构名字，加载中文命名实体识别的预训练模型MSRA_NER_BERT_BASE_ZH
recognizer=hanlp.load(hanlp.pretrained.ner.MSRA_NER_ALBERT_BASE_ZH)
recognizer(list('上海华安工业（集团）公司董事长谭旭光和秘书张晚霞来到美 国纽约现代艺术博物馆参观。'))
# 返回结果是一个装有n个元组的列表, 每个元组代表一个命名实体, 元组中的每一项分别代表具体的命名实体, 如: '上海华安工业（集团）公司';
#  命名实体的类型, 如: 'NT'-机构名; 命名实体的开始索引和结束索引, 如: 0, 12.

# 加载英文命名实体识别的预训练模型CONLL03_NER_BERT_BASE_UNCASED_EN
recognizer1=hanlp.load(hanlp.pretrained.ner.CONLL03_NER_BERT_BASE_CASED_EN)
recognizer1(["President", "Obama", "is", "speaking", "at", "the", "White", "House"])
#[('Obama', 'PER', 1, 2), ('White House', 'LOC', 6, 8)]

KeyboardInterrupt: 

In [ ]:
#词性标注
#词性标注的作用:
# 词性标注以分词为基础, 是对文本语言的另一个角度的理解, 
# 因此也常常成为AI解决NLP领域高阶任务的重要基础环节.
import jieba.posseg as pseg
pseg.lcut('西巴罗马给死噶起飞')
#rr: 人称代词v: 动词n: 名词vn: 动名词
tagger=hanlp.load(hanlp.pretrained.pos.CTB5_POS_RNN_FASTTEXT_ZH)
tagger(['我', '的', '希望', '是', '希望', '和平'])
# ['PN', 'DEG', 'NN', 'VC', 'VV', 'NN']
tagger1=hanlp.load(hanlp.pretrained.pos.PTB_POS_RNN_FASTTEXT_EN)
tagger1(['I', 'banked', '2', 'dollars', 'in', 'a', 'bank', '.'])
# ['PRP', 'VBD', 'CD', 'NNS', 'IN', 'DT', 'NN', '.']

['PRP', 'VBD', 'CD', 'NNS', 'IN', 'DT', 'NN', '.']

In [ ]:
#导入对象保存和加载的joblib
import joblib
#导入映射器
from keras.preprocessing.text import Tokenizer
# 假定vocab为语料集所有不同词汇集合
vocab = {"周杰伦", "陈奕迅", "王力宏", "李宗盛", "吴亦凡", "鹿晗"}
#实例化对象
t=Tokenizer(num_words=None,char_level=False)
#使用映射器拟合现有文本
t.fit_on_texts(vocab)
for token in vocab:
    zero_list=[0]*len(vocab)
    # 使用映射器转化现有文本数据, 每个词汇对应从1开始的自然数
    # 返回样式如: [[2]], 取出其中的数字需要使用[0][0]
    token_index=t.texts_to_sequences([token])[0][0]-1
    zero_list[token_index]=1
    print(token,"的独热编码为：",zero_list)
#baocun
tokenize_path="./Tokenizer"
joblib.dump(t,tokenize_path)
#鹿晗 的独热编码为： [1, 0, 0, 0, 0, 0]
# 周杰伦 的独热编码为： [0, 1, 0, 0, 0, 0]
# 陈奕迅 的独热编码为： [0, 0, 1, 0, 0, 0]
# 王力宏 的独热编码为： [0, 0, 0, 1, 0, 0]
# 吴亦凡 的独热编码为： [0, 0, 0, 0, 1, 0]
# 李宗盛 的独热编码为： [0, 0, 0, 0, 0, 1]
# ['./Tokenizer']  #乱序



陈奕迅 的独热编码为： [1, 0, 0, 0, 0, 0]
李宗盛 的独热编码为： [0, 1, 0, 0, 0, 0]
王力宏 的独热编码为： [0, 0, 1, 0, 0, 0]
吴亦凡 的独热编码为： [0, 0, 0, 1, 0, 0]
鹿晗 的独热编码为： [0, 0, 0, 0, 1, 0]
周杰伦 的独热编码为： [0, 0, 0, 0, 0, 1]


['./Tokenizer']

In [ ]:
t=joblib.load(tokenize_path)
token="鹿晗"
token_index=t.texts_to_sequences([token])[0][0]-1  
#经过映射以后的词汇 编号从1开始 所以需要-1
zero_list=[0]*len(vocab)
#命令索引
zero_list[token_index]=1
print(token,"独热编码是",zero_list)

鹿晗 独热编码是 [0, 0, 0, 0, 1, 0]


In [ ]:
dirs='./data'
if not os.path.exists(dirs):
    os.mkdir(dirs)
    

In [ ]:
import fasttext
# 使用fasttext的train_unsupervised(无监督训练方法)进行词向量的训练
# 它的参数是数据集的持久化文件路径'data/fil9'
model=fasttext.train_unsupervised('./data/data/fil9')

Read 124M words
Number of words:  218316
Number of labels: 0
Progress: 100.0% words/sec/thread:   29604 lr:  0.000000 avg.loss:  1.719309 ETA:   0h 0m 0s


In [ ]:
# 通过get_word_vector方法来获得指定词汇的词向量
model.get_word_vector('the')

array([ 5.24385631e-01,  3.63799453e-01, -8.93141609e-04,  3.18321288e-01,
       -7.80495703e-02,  2.17307642e-01, -3.84163707e-01,  7.33489171e-02,
       -1.94568530e-01, -2.87327379e-01, -1.46425627e-02,  4.43825543e-01,
       -4.28206652e-01, -9.51399878e-02, -1.85428217e-01, -8.90882462e-02,
       -4.02024831e-04,  2.84576938e-02, -4.70436253e-02,  1.25950240e-02,
        3.10158700e-01, -1.04337022e-01,  2.01025695e-01, -1.15471885e-01,
       -1.95134953e-01,  7.65331239e-02,  2.65599508e-02, -1.36771768e-01,
       -1.98762909e-01,  2.13085145e-01,  1.17220074e-01,  1.09828793e-01,
        2.55944550e-01, -1.82137817e-01, -7.80265555e-02,  2.03247249e-01,
        6.50833994e-02, -1.78350970e-01,  4.20766249e-02,  2.95423716e-01,
        1.30491361e-01,  3.77705425e-01,  1.78835407e-01, -5.89264669e-02,
        1.17069207e-01, -2.28810430e-01, -2.40911469e-02, -4.32535447e-02,
       -1.34164900e-01,  7.06495270e-02,  1.36182994e-01, -1.98625341e-01,
        1.68109033e-02,  

In [ ]:
# 在训练词向量过程中, 我们可以设定很多常用超参数来调节我们的模型效果, 如:
# 无监督训练模式: 'skipgram' 或者 'cbow', 默认为'skipgram', #给词推出上下文
# 在实践中，skipgram模式在利用子词方面比cbow更好.
# 词嵌入维度dim: 默认为100, 但随着语料库的增大, 词嵌入的维度往往也要更大.
# 数据循环次数epoch: 默认为5, 但当你的数据集足够大, 可能不需要那么多次.
# 学习率lr: 默认为0.05, 根据经验, 建议选择[0.01，1]范围内.
# 使用的线程数thread: 默认为12个线程, 一般建议和你的cpu核数相同.
model = fasttext.train_unsupervised('data/data/fil9', "cbow", dim=300, epoch=10, lr=0.1, thread=8)

Read 124M words
Number of words:  218316
Number of labels: 0
Progress: 100.0% words/sec/thread:   54525 lr:  0.000000 avg.loss: 10.749687 ETA:   0h 0m 0s


In [ ]:
# 检查单词向量质量的一种简单方法就是查看其邻近单词, 通过我们主观来判断这些邻近单词是否与目标单词相关来粗略评定模型效果好坏.

# 查找"运动"的邻近单词, 我们可以发现"体育网", "运动汽车", "运动服"等. 
model.get_nearest_neighbors('sports')
# [(0.8414610624313354, 'sportsnet'), (0.8134572505950928, 'sport'), 
# (0.8100415468215942, 'sportscars'), (0.8021156787872314, 'sportsground'),
#  (0.7889881134033203, 'sportswomen'), (0.7863013744354248, 'sportsplex')]

[(0.4674226939678192, 'football'),
 (0.463969349861145, 'sport'),
 (0.4284372925758362, 'basketball'),
 (0.3893170654773712, 'athletic'),
 (0.3887898623943329, 'teams'),
 (0.3784802556037903, 'interuniversity'),
 (0.3665440082550049, 'recreation'),
 (0.35497987270355225, 'baseball'),
 (0.3457636833190918, 'sporting'),
 (0.34530219435691833, 'club')]

In [ ]:
# 使用fasttext工具实现word2vec的训练和使用
# 第一步: 获取训练数据
# 第二步: 训练词向量
# 第三步: 模型超参数设定
# 第四步: 模型效果检验
# 第五步: 模型的保存与重加载
# 5.
model.save_model("fil9.bin")
model=fasttext.load_model("fil9.bin")
model.get_word_vector("the")

array([-1.00355935e+00,  1.01976466e+00,  8.73386979e-01,  1.63665503e-01,
       -5.52194059e-01, -1.72674978e+00,  1.16322112e+00, -1.29020765e-01,
        1.67486310e+00,  2.19617307e-01, -1.05264235e+00, -5.25729060e-01,
       -2.42879599e-01, -5.91217339e-01,  3.72944713e-01, -2.64449269e-01,
        4.54849809e-01,  1.25833794e-01,  2.42019176e+00,  4.48823124e-01,
        8.76403600e-02, -5.12947917e-01, -6.50572121e-01, -1.38296410e-01,
       -5.49582064e-01,  9.02267516e-01, -1.99012315e+00, -7.34647512e-01,
        1.32805973e-01,  3.73237342e-01,  1.97906208e+00, -3.68038744e-01,
        8.43004823e-01, -8.20355475e-01,  1.33319020e+00, -3.31668854e-01,
        5.47624588e-01,  3.08358878e-01, -7.75331140e-01,  1.07636487e+00,
       -2.80400962e-01,  2.79517794e+00,  3.56986076e-01, -2.76972115e-01,
       -7.63467252e-01, -3.35802361e-02, -8.03458631e-01, -2.47910786e+00,
        6.64144814e-01,  1.70741230e-01,  9.78121087e-02, -1.49355459e+00,
        6.51734352e-01,  

In [ ]:
import torch
import json
import fileinput
from torch.utils.tensorboard import SummaryWriter
#实例化对象
writer= SummaryWriter()
#随机100*50的矩阵，代表100个词汇，每个词汇被表示成50维的向量
embedded=torch.randn(100,50)
#daoru
meta=list(map(lambda x:x.strip(),fileinput.FileInput("./vocab100.csv")))
writer.add_embedding(embedded,metadata=meta)
writer.close()
# tensorboard --logdir runs --host 0.0.0.0

FileNotFoundError: [Errno 2] No such file or directory: './vocab100.csv'

In [ ]:
from keras.preprocessing import sequence
cutlen=10
def padding(x_train):
    return sequence.pad_sequences(x_train,cutlen)
# 假定x_train里面有两条文本, 一条长度大于10, 一天小于10
x_train = [[1, 23, 5, 32, 55, 63, 2, 21, 78, 32, 23, 1],
           [2, 32, 1, 23, 1]]
res=padding(x_train)
print(res)

[[ 5 32 55 63  2 21 78 32 23  1]
 [ 0  0  0  0  0  2 32  1 23  1]]


In [ ]:
# 一般n-gram中的n取2或者3, 这里取2为例
ngram_range = 2
def create_ngram_set(input_list):
    return set(zip(*[input_list[i:]  for i in range(ngram_range)]))
input_list=[1,3,2,1,5,3]
res=create_ngram_set(input_list)
print(res)
# {(3, 2), (1, 3), (2, 1), (1, 5), (5, 3)}
# 1,3,2,1,5,和3,2,1,5,3进行zip组合

{(3, 2), (1, 3), (2, 1), (1, 5), (5, 3)}


In [ ]:
# 回译数据增强实现:
# 假设取两条已经存在的正样本和两条负样本
# 将基于这四条样本产生新的同标签的四条样本
p_sample1 = "酒店设施非常不错"
p_sample2 = "这家价格很便宜"
n_sample1 = "拖鞋都发霉了, 太差了"
n_sample2 = "电视不好用, 没有看到足球"

from googletrans import Translator
translator=Translator()
translations=translator.translate([p_sample1,p_sample2,n_sample1,n_sample2],dest='ko')
ko_res=list(map(lambda x:x.text,translations))
#zhongjian hanwen
print('中间结果',ko_res)

translations=translator.translate(ko_res,dest='zh-cn')
cn_res=list(map(lambda x:x.text,translations))
print('最终结果',cn_res)

ConnectError: [Errno 101] Network is unreachable

In [ ]:
array = ['c', 'a', 'c', 'd', 'b', 'b', 'a', 'a', 'f']

# method-1 转换为集合
print(list(set(array)))

# method-2 列表推导式 1
uniq = []
[uniq.append(x) for x in array if x not in uniq]
print(uniq)

# method-3 列表推导式 2
print([x for y, x in enumerate(array) if array.index(x) == y])

['d', 'c', 'b', 'a', 'f']
['c', 'a', 'd', 'b', 'f']
['c', 'a', 'd', 'b', 'f']


In [14]:
#Bmm运算
input= torch.randn(10,3,4)
mat2=torch.randn(10,4,5)
res=torch.bmm(input,mat2)
res.size()

NameError: name 'torch' is not defined