In [2]:
import torch
import torch.nn as nn
rnn=nn.RNN(5,6,1) 
# input_size: 输入张量x中特征维度的大小. 5
# hidden_size: 隐层张量h中特征维度的大小.6
# num_layers: 隐含层的数量 1
input=torch.randn(1,3,5)#sequence_length  batch_size input_size
print(input)
h0=torch.randn(1,3,6) #num_layers*num_directions(层数*网络方向数) batch_size hidden_size 
print(h0)
output,hn=rnn(input,h0)
output,hn,hn.shape


tensor([[[-0.0695,  0.2277, -0.9907, -0.5617,  0.4837],
         [ 0.3208, -0.3333,  0.4655,  0.2692, -0.5449],
         [-0.9745,  0.6336, -0.7371,  0.6157, -1.5140]]])
tensor([[[ 0.6994,  0.9750,  2.3658,  0.0056, -1.4974,  1.3758],
         [ 0.1764, -0.1875, -0.0397,  1.5075,  0.5834, -1.7453],
         [-0.0845,  0.2301, -1.2351, -0.3110,  0.6215,  0.2494]]])


(tensor([[[-0.7691, -0.4026, -0.5119,  0.7590,  0.7891,  0.8076],
          [-0.0718, -0.5620,  0.3941,  0.7027, -0.1661,  0.4710],
          [ 0.0847,  0.0332,  0.3617, -0.2823,  0.1825,  0.4442]]],
        grad_fn=<StackBackward>),
 tensor([[[-0.7691, -0.4026, -0.5119,  0.7590,  0.7891,  0.8076],
          [-0.0718, -0.5620,  0.3941,  0.7027, -0.1661,  0.4710],
          [ 0.0847,  0.0332,  0.3617, -0.2823,  0.1825,  0.4442]]],
        grad_fn=<StackBackward>),
 torch.Size([1, 3, 6]))

In [3]:
# 定义LSTM的参数含义: (input_size, hidden_size, num_layers)
# 定义输入张量的参数含义: (sequence_length, batch_size, input_size)
# 定义隐藏层初始张量和细胞初始状态张量的参数含义:
# (num_layers * num_directions, batch_size, hidden_size)
# input: 输入张量x. #sequence_length  batch_size input_size
# h0: 初始化的隐层张量h. #num_layers*num_directions(层数*网络方向数) batch_size hidden_size
# c0: 初始化的细胞状态张量c.
import torch.nn as nn
import torch
lstm=nn.LSTM(5,6,2)
input= torch.randn(1,3,5)
h0=torch.randn(2,3,6)
c0=torch.randn(2,3,6)
output,(hn,cn)=lstm(input,(h0,c0))
output

tensor([[[-0.0943, -0.0864, -0.1128,  0.1550, -0.1884, -0.3071],
         [-0.3581, -0.2900, -0.3129,  0.0009,  0.1982, -0.1814],
         [ 0.6345, -0.3270,  0.3803, -0.5738,  0.2252, -0.1469]]],
       grad_fn=<StackBackward>)

In [4]:
# nn.GRU类初始化主要参数解释:
# input_size: 输入张量x中特征维度的大小.
# hidden_size: 隐层张量h中特征维度的大小.
# num_layers: 隐含层的数量.
# bidirectional: 是否选择使用双向LSTM, 如果为True, 则使用; 默认不使用.
# nn.GRU类实例化对象主要参数解释:
# input: 输入张量x.#sequence_length  batch_size input_size
# h0: 初始化的隐层张量h. #num_layers*num_directions(层数*网络方向数) batch_size hidden_size
GRU=nn.GRU(5,6,2)
input=torch.randn(1,3,5)
h0=torch.randn(2,3,6)
output,hn=GRU(input,h0)
output


tensor([[[ 0.1380, -0.2547,  0.4015, -0.3906,  0.0390,  0.6201],
         [ 0.3024,  0.3568,  0.0212, -0.3250, -0.1537,  0.8749],
         [ 0.7009,  0.2588,  0.7416, -0.9569,  0.6672, -0.4508]]],
       grad_fn=<StackBackward>)

In [5]:
#Bmm运算
input= torch.randn(10,3,4)
mat2=torch.randn(10,4,5)
res=torch.bmm(input,mat2)
res.size()

torch.Size([10, 3, 5])

In [21]:
# 第一步: 导入必备的工具包
from io import open #导入打开方法
import glob
import os
import string
import unicodedata
import random
import time
import math
import torch
import torch.nn as nn 
import matplotlib.pyplot as plt

# 第二步: 对data文件中的数据进行处理，满足训练要求.

all_letters=string.ascii_letters+" .,;'"# 获取所有常用字符包括字母和常用标点
n_letters=len(all_letters)# 获取常用字符数量
# print("n_letter:",n_letters)
def unicodeToAscii(s):
    # 字符规范化之unicode转Ascii函数:# 我们认为这个函数的作用就是去掉一些语言中的重音标记
    # 如: Ślusàrski ---> Slusarski
    return  ''.join(
        c for  c in unicodedata.normalize('NFD',s)
        if unicodedata.category(c)!='Mn' and c in all_letters
    )
# s = "Ślusàrski"
# a = unicodeToAscii(s)
# print(a)
data_path='./data/data/names/'
# 构建一个从持久化文件中读取内容到内存的函数/:  #磁盘文件就是持久化文件
def  readlines(filename):
    """从文件中读取每一行加载到内存中形成列表"""
    # 打开指定文件并读取所有内容, 使用strip()去除两侧空白符, 然后以'\n'进行切分
    lines = open(filename,encoding='utf-8').read().strip().split('\n')
    #每一个lines列表中的名字进行ascii转换
    return [unicodeToAscii(line) for line  in  lines]
# filename = data_path +'Chinese.txt'
# lines =readlines(filename)
# print(lines[:20])


# 构建人名类别（所属的语言）列表与人名对应关系字典:
# 构建的category_lines形如：{"English":["Lily", "Susan", "Kobe"], "Chinese":["Zhang San", "Xiao Ming"]}
category_lines = {}
# all_categories形如： ["English",...,"Chinese"]
all_categories = []

# 读取指定路径下的txt文件， 使用glob，path中可以使用正则表达式
for filename in glob.glob(data_path+'*txt'):
    # 获取每个文件的文件名, 就是对应的名字类别
    category=os.path.splitext(os.path.basename(filename))[0]
    all_categories.append(category)
    lines=readlines(filename)
    category_lines[category]=lines
n_categories=len(all_categories)
print('n_categories:',n_categories)
# 随便查看其中的一些内容
print(category_lines['Italian'][:5])

n_categories: 18
['Abandonato', 'Abatangelo', 'Abatantuono', 'Abate', 'Abategiovanni']


In [41]:
# 将人名转化为对应onehot张量表示:
# 将字符串(单词粒度)转化为张量表示，如："ab" --->
# tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0.]],

#        [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0.]]])

def lineToTensor(line):
    """将人名转化为对应onehot张量表示, 参数line是输入的人名"""
    # 首先初始化一个0张量, 它的形状(len(line), 1, n_letters) 
    # 代表人名中的每个字母用一个1 x n_letters的张量表示.
    tensor=torch.zeros(len(line),1,n_letters)#n_letters多少个字母
    for li,letter in enumerate(line):
        tensor[li][0][all_letters.find(letter)]=1
    return tensor
# line='Bai'
# line_tensor=lineToTensor(line)
# print(line_tensor)

# 第三步: 构建RNN模型
class RNN(nn.Module):
    def __init__(self,input_size,hidden_size,output_size,num_layers=1):
        """初始化函数中有4个参数, 分别代表RNN输入最后一维尺寸, RNN的隐层最后一维尺寸, RNN层数"""
        super(RNN,self).__init__()
        self.hidden_size=hidden_size
        self.num_layes=num_layers
        #实例化RNN
        self.rnn=nn.RNN(input_size,hidden_size,num_layers)
        #实例化线性层  #将rnn的输出维度 转换成指定的outputsize的指定维度
        self.linear=nn.Linear(hidden_size,output_size)
        #实例化nn中的softmax  #获得类别结果
        self.softmax=nn.LogSoftmax(dim=-1)#

    def forward(self,input,hidden):
        """完成传统RNN中的主要逻辑, 输入参数input代表输入张量, 它的形状是1 x n_letters
        hidden代表RNN的隐层张量, 它的形状是self.num_layers x 1 x self.hidden_size"""
        # 因为预定义的nn.RNN要求输入维度一定是三维张量, 因此在这里使用unsqueeze(0)扩展一个维度
        input=input.unsqueeze(0)
        rr,hn=self.rnn(input,hidden)
        return self.softmax(self.linear(rr)),hn

    def initHidden(self):
        """初始化隐层张量"""
        # 初始化一个（self.num_layers, 1, self.hidden_size）形状的0张量    
        return torch.zeros(self.num_layes,1,self.hidden_size)


In [43]:
# 使用nn.LSTM构建完成LSTM使用类
class LSTM(nn.Module):
    def __init__(self,input_size,hidden_size,output_size,num_layers=1):
        super().__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers

        #实例化
        self.lstm=nn.LSTM(input_size,hidden_size,num_layers)
        #实例化线性层，控制输出维度
        self.linear=nn.Linear(hidden_size,out_features=output_size)
        #获得线性层的输出结果
        self.softmax=nn.LogSoftmax(dim=-1)


    def forward(self,input,hidden,c):
        # c  cell 细胞状态
        input=input.unsqueeze(0)
        rr,(hn,c)=self.lstm(input,(hidden,c))
        return self.softmax(self.linear(rr)),hn,c

    def initHiddenAndC(self):
        c=hidden=torch.zeros(self.num_layers,1,self.hidden_size)
        return hidden,c


In [52]:
# 使用nn.GRU构建完成传统RNN使用类

# GRU与传统RNN的外部形式相同, 都是只传递隐层张量, 因此只需要更改预定义层的名字

class GRU(nn.Module):
    def __init__(self,input_size,hidden_size,output_size,num_layers=1):
        super(GRU,self).__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers

        self.gru=nn.GRU(input_size,hidden_size,num_layers)
        self.linear=nn.Linear(hidden_size,output_size)
        self.softmax=nn.LogSoftmax(dim=-1)

    def  forward(self,input,hidden):
        input=input.unsqueeze(0)
        rr,hn=self.gru(input,hidden)
        return self.softmax(self.linear(rr)),hn
    
    def initHidden(self):
        return torch.zeros(self.num_layers,1,self.hidden_size) #3ceng



In [45]:
#实例化参数
#因为是onehot编码，输入张量就是最后一维度，n_letters
input_size=n_letters
n_hidden=128
output_size=n_categories #shuchu 总类别数
num_layers=1#默认

In [47]:
# 假如我们以一个字母B作为RNN的首次输入, 它通过lineToTensor转为张量
# 因为我们的lineToTensor输出是三维张量, 而RNN类需要的二维张量 但是foward内填充了一位
# 因此需要使用squeeze(0)降低一个维度
input = lineToTensor('B').squeeze(0)

# 初始化一个三维的隐层0张量, 也是初始的细胞状态张量
hidden = c = torch.zeros(1, 1, n_hidden)

In [53]:
rnn=RNN(n_letters,n_hidden,n_categories)
lstm=LSTM(n_letters,n_hidden,n_categories)
gru=GRU(n_letters,n_hidden,n_categories)
rnn_output,next_hidden=rnn(input,hidden)
lstm_output,next_hidden,c=lstm(input,hidden,c)
gru_output,next_hidden=gru(input,hidden)

In [63]:
# 第四步: 构建训练函数并进行训练
# 从输出结果中获得指定类别函数
def categoryFromOutput(output):
    """从输出结果中获得指定类别, 参数为输出张量output"""
    # 从输出张量中返回最大的值和索引对象, 我们这里主要需要这个索引
    top_n,top_i = output.topk(1)# top_i对象中取出索引的值 topk返回值和索引
    category_i=top_i[0].item()
    return all_categories[category_i],category_i # 根据索引值获得对应语言类别, 返回语言类别和索引值

# output=gru_output
# category,category_i=categoryFromOutput(output)
# print(category,category_i)

# 随机生成训练数据:.
def randomTrainingExample():
    #随机选择一个类别
    category=random.choice(all_categories)
    #该类别选择一个名字
    line= random.choice(category_lines[category])
    #将类别封装成tensor
    category_tensor=torch.tensor([all_categories.index(category)],dtype=torch.long)
    #将名字转换成onehot张量表示
    line_tensor=lineToTensor(line)
    return category,line,category_tensor,line_tensor


# # 我们随机取出十个进行结果查看
# for i in range(10):
#     category, line, category_tensor, line_tensor = randomTrainingExample()
#     print('category =', category, '/ line =', line, '/ category_tensor =', category_tensor,'/ line_tensor',line_tensor)

# 构建传统RNN训练函数:
criterion=nn.NLLLoss()
learning_rate=0.005
def trainRNN(category_tensor,line_tensor):
    hidden=rnn.initHidden()
    rnn.zero_grad()
    # 下面开始进行训练, 将训练数据line_tensor的每个字符逐个传入rnn之中, 得到最终结果
    for i in range(line_tensor):
        output,hidden=rnn(line_tensor[i],hidden) #hidden循环 只需要最后一个outPUT
    
    loss=criterion(output.squeeze(0),category_tensor)
    loss.backward()
    for p in rnn.parameters():
        # 将参数的张量表示与参数的梯度乘以学习率的结果相加以此来更新参数
        p.data.add_(-learning_rate,p.grad.data)  #add_原地迭代
    return output,loss.item()


    